// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package go_reversestr_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReverserClient is the client API for Reverser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverserClient interface {
	ReverseString(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type reverserClient struct {
	cc grpc.ClientConnInterface
}

func NewReverserClient(cc grpc.ClientConnInterface) ReverserClient {
	return &reverserClient{cc}
}

func (c *reverserClient) ReverseString(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/reversestr.Reverser/ReverseString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverserServer is the server API for Reverser service.
// All implementations must embed UnimplementedReverserServer
// for forward compatibility
type ReverserServer interface {
	ReverseString(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedReverserServer()
}

// UnimplementedReverserServer must be embedded to have forward compatible implementations.
type UnimplementedReverserServer struct {
}

func (UnimplementedReverserServer) ReverseString(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseString not implemented")
}
func (UnimplementedReverserServer) mustEmbedUnimplementedReverserServer() {}

// UnsafeReverserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverserServer will
// result in compilation errors.
type UnsafeReverserServer interface {
	mustEmbedUnimplementedReverserServer()
}

func RegisterReverserServer(s grpc.ServiceRegistrar, srv ReverserServer) {
	s.RegisterService(&Reverser_ServiceDesc, srv)
}

func _Reverser_ReverseString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverserServer).ReverseString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reversestr.Reverser/ReverseString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverserServer).ReverseString(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Reverser_ServiceDesc is the grpc.ServiceDesc for Reverser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reverser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reversestr.Reverser",
	HandlerType: (*ReverserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReverseString",
			Handler:    _Reverser_ReverseString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reversestr/reversestr.proto",
}
